services:
  web:
    image: nginx:1.29-alpine
    volumes:
    - static_apresentacao:/usr/share/nginx/html:ro
    environment:
      - TZ=America/Sao_paulo
    ports:
    - "8080:80"
    depends_on:
      builder:
        condition: service_completed_successfully

  builder:
    build: .
    volumes:
    - static_apresentacao:/app/dist/apresentacao/browser

volumes:
  static_apresentacao:
